version: '3'

services:
  app:
    build: .
    ports:
      - "4001:4001"
    working_dir: "/src"
    volumes:
      - "./src:/src"
      - node_modules_volume:/src/node_modules
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    networks:
      - filma-api_default
networks:
  filma-api_default:
    external: true
volumes:
  node_modules_volume: